{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  {
    flags = {};
    package = {
      specVersion = "2.0";
      identifier = { name = "gi-gtksource5"; version = "5.0.2"; };
      license = "LGPL-2.1-only";
      copyright = "";
      maintainer = "Iñaki García Etxebarria";
      author = "Iñaki García Etxebarria";
      homepage = "https://github.com/haskell-gi/haskell-gi";
      url = "";
      synopsis = "GtkSource 5.x bindings";
      description = "Bindings for GtkSource 5.x, autogenerated by haskell-gi.";
      buildType = "Custom";
      setup-depends = [
        (hsPkgs.buildPackages.base or (pkgs.buildPackages.base or (errorHandler.setupDepError "base")))
        (hsPkgs.buildPackages.Cabal or (pkgs.buildPackages.Cabal or (errorHandler.setupDepError "Cabal")))
        (hsPkgs.buildPackages.haskell-gi or (pkgs.buildPackages.haskell-gi or (errorHandler.setupDepError "haskell-gi")))
        (hsPkgs.buildPackages.gi-cairo or (pkgs.buildPackages.gi-cairo or (errorHandler.setupDepError "gi-cairo")))
        (hsPkgs.buildPackages.gi-pango or (pkgs.buildPackages.gi-pango or (errorHandler.setupDepError "gi-pango")))
        (hsPkgs.buildPackages.gi-gtk4 or (pkgs.buildPackages.gi-gtk4 or (errorHandler.setupDepError "gi-gtk4")))
        (hsPkgs.buildPackages.gi-gio or (pkgs.buildPackages.gi-gio or (errorHandler.setupDepError "gi-gio")))
        (hsPkgs.buildPackages.gi-gdkpixbuf or (pkgs.buildPackages.gi-gdkpixbuf or (errorHandler.setupDepError "gi-gdkpixbuf")))
        (hsPkgs.buildPackages.gi-gdk4 or (pkgs.buildPackages.gi-gdk4 or (errorHandler.setupDepError "gi-gdk4")))
        (hsPkgs.buildPackages.gi-gobject or (pkgs.buildPackages.gi-gobject or (errorHandler.setupDepError "gi-gobject")))
        (hsPkgs.buildPackages.gi-glib or (pkgs.buildPackages.gi-glib or (errorHandler.setupDepError "gi-glib")))
        (hsPkgs.buildPackages.gi-atk or (pkgs.buildPackages.gi-atk or (errorHandler.setupDepError "gi-atk")))
        ];
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."haskell-gi-base" or (errorHandler.buildDepError "haskell-gi-base"))
          (hsPkgs."haskell-gi" or (errorHandler.buildDepError "haskell-gi"))
          (hsPkgs."haskell-gi-overloading" or (errorHandler.buildDepError "haskell-gi-overloading"))
          (hsPkgs."gi-cairo" or (errorHandler.buildDepError "gi-cairo"))
          (hsPkgs."gi-pango" or (errorHandler.buildDepError "gi-pango"))
          (hsPkgs."gi-gtk4" or (errorHandler.buildDepError "gi-gtk4"))
          (hsPkgs."gi-gio" or (errorHandler.buildDepError "gi-gio"))
          (hsPkgs."gi-gdkpixbuf" or (errorHandler.buildDepError "gi-gdkpixbuf"))
          (hsPkgs."gi-gdk4" or (errorHandler.buildDepError "gi-gdk4"))
          (hsPkgs."gi-gobject" or (errorHandler.buildDepError "gi-gobject"))
          (hsPkgs."gi-glib" or (errorHandler.buildDepError "gi-glib"))
          (hsPkgs."gi-atk" or (errorHandler.buildDepError "gi-atk"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
          (hsPkgs."text" or (errorHandler.buildDepError "text"))
          (hsPkgs."transformers" or (errorHandler.buildDepError "transformers"))
          ] ++ (pkgs.lib).optional (compiler.isGhc && ((compiler.version).ge "8.2" && (compiler.version).lt "8.3")) (hsPkgs."haskell-gi-overloading" or (errorHandler.buildDepError "haskell-gi-overloading"));
        pkgconfig = [
          (pkgconfPkgs."gtksourceview-5" or (errorHandler.pkgConfDepError "gtksourceview-5"))
          ];
        buildable = true;
        };
      };
    }